server:
  port: 8888

#数据库连接信息
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/task?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis
mybatis:
  mapper-locations: classpath:dao/*Dao.xml
  type-aliases-package: com.mofei.springbootmybatis.domain

